using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

public class ModelOnClick : MonoBehaviour
{
    public GameObject ModelToChange;
    private MeshRenderer meshRenderer;

    private int min;              //ノ蟪]w思骗p瑟氦滥
    private int sec;              //ノ蟪]w思骗p瑟含砑
    public int timer;            //思骗p筛g传衡毫`砑
    private float TempNumber;             //放

    public Text timertext;         //]we杯思骗p瑟氦濡r
    public Text nametoshow;



    void Start()
    {
        meshRenderer = ModelToChange.GetComponent<MeshRenderer>();

    }

    private void Update()
    {
        CityTemp TempScript = GetComponent<CityTemp>();
        TempNumber = TempScript.CountyTemp;
    }

    private void OnMouseDown()
    {
        Debug.Log("Click!");
        sec = 2;
        StartCoroutine(StartCountdown());
    }


    IEnumerator StartCountdown()
    {
        meshRenderer.material.color = Color.red;

        timertext.text = string.Format("{0}:{1}", min.ToString("00"), sec.ToString("00"));
        nametoshow.text = string.Format("{0}{b放:{1}", ModelToChange.name.ToString(), TempNumber.ToString("00.0"));


        timer = (min * 60) + sec;       //N啥〈衡艾砑

        while (timer > 0)                   //pG啥々|ゼ挡
        {
            yield return new WaitForSecondsRealtime(1); //单预@恙AΩ磅

            timer--;                        //`砑拼 1
            sec--;                            //N砑拼 1

            if (sec < 0 && min > 0)         //pG砑片 0 Bだ牧j 0
            {
                min --;                     //Nだ牧搭h 1
                sec = 59;                     //AN砑瞥] 59
            }
            else if (sec < 0 && min == 0)   //pG砑片 0 Bだ牧j 0
            {
                sec = 0;                      //]w砑频ォ 0
            }
            timertext.text = string.Format("{0}:{1}", min.ToString("00"), sec.ToString("00"));
        }

        yield return new WaitForSecondsRealtime(1);   //啥〉钵舢伞A陪ボ 00:00 氨d@

        nametoshow.text = string.Empty;
        meshRenderer.material.color = Color.yellow;
        sec = 2;
    }
}